apiVersion: v1  
kind: Template  
metadata:  
  name: selenium-node-chrome  
  annotations:  
    description: "Selenium Node with Google Chrome browser"  
    iconClass: "icon-selenium"  
    tags: "selenium,node,chrome"  
objects:
- apiVersion: v1  
  kind: DeploymentConfig  
  metadata:  
    name: selenium-node-chrome  
    labels:  
      app: selenium  
      browser: chrome  
  spec:
    replicas: 2
    selector:  
      browser: chrome  
    template:  
      metadata:  
        name: selenium-node-chrome-master  
        labels:  
          browser: chrome  
          app: selenium  
      spec:  
        containers:  
        - env:  
          - name: JAVA_OPTS  
            value: ${JAVA_OPTS}  
          - name: SE_OPTS  
            value: ${SE_OPTS}  
          - name: HUB_PORT_4444_TCP_ADDR  
            value: ${HUB_PORT_4444_TCP_ADDR}  
          - name: HUB_PORT_4444_TCP_PORT  
            value: ${HUB_PORT_4444_TCP_PORT}  
          - name: REMOTE_HOST  
            value: ${REMOTE_HOST}  
          - name: TZ  
            value: Asia/Singapore  
          image: selenium/node-chrome
          name: master
          ports:  
          - containerPort: 4444  
            protocol: TCP  
          - containerPort: 5555  
            protocol: TCP
          resources: 
            requests: 
              memory: "${REQUEST_MEM}" 
              cpu: "${REQUEST_CPU}" 
            limits: 
              memory: "${LIMIT_MEM}" 
              cpu: "${LIMIT_CPU}" 
- apiVersion: v1  
  kind: Service  
  metadata:  
    name: selenium-node-chrome  
    labels:  
      app: selenium  
      browser: chrome  
  spec:  
    selector:  
      browser: chrome  
    type: ClusterIP  
    ports:  
    - name: node-port  
      port: 5555  
      targetPort: 5555  
      protocol: TCP  
    - name: node-port-grid  
      port: 4444  
      targetPort: 4444  
      protocol: TCP
parameters:  
  - name: JAVA_OPTS  
    description: Options for the Java command  
    value: "-Xmx512m -Dselenium.LOGGER.level=WARNING"  
  - name: SE_OPTS  
    description: Options for the Node  
    value: ""  
  - name: HUB_PORT_4444_TCP_ADDR  
    description: The Hub to connect to  
    value: "selenium-hub"  
  - name: HUB_PORT_4444_TCP_PORT  
    description: The Hub port to connect to  
    value: "4444"  
  - name: REMOTE_HOST  
    description: The remote host  
    value: ""  
  - name: NODE_ID  
    description: Unique ID assigned to the node  
    generate: expression  
    from: '[a-z]{4}'
  - description: Minimum gauranteed CPU 
    name: REQUEST_CPU 
    value: "100m" 
  - description: Minimum gauranteed Memory 
    name: REQUEST_MEM 
    value: "200Mi" 
  - description: Max  Memory 
    name: LIMIT_MEM 
    value: "500Mi" 
  - description: Max  CPU 
    name: LIMIT_CPU 
    value: "200m" 